# Generated by Django 4.1.5 on 2023-01-23 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prescriptor",
            fields=[
                (
                    "id_prescriptor",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("empresa", models.CharField(blank=True, max_length=50, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("movil", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
