# Generated by Django 4.1.5 on 2023-01-24 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tarifas",
            fields=[
                (
                    "id_tarifas",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("comision_de_la_tarifa", models.FloatField()),
            ],
        ),
    ]
