# Generated by Django 4.1.5 on 2023-01-24 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("prescriptor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encargo",
            fields=[
                (
                    "numero_expediente",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "idioma_encargo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Castellano", "Castellano"),
                            ("Catalan", "Catalan"),
                            ("Ingles", "Ingles"),
                            ("Frances", "Frances"),
                            ("OTRO", "OTRO"),
                        ],
                        default="Castellano",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("via_encargo", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "objetivo_tasacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("numero_de_elementos", models.IntegerField(blank=True, null=True)),
                (
                    "documentacion",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "ID_cliente",
                    models.ForeignKey(
                        default="7b1f8f5a-7353-4683-b4ea-5c8e2c1f91bd",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "ID_prescriptor",
                    models.ForeignKey(
                        default="7b1f8f5a-7353-4683-b4ea-5c8e2c1f91bd",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="prescriptor.prescriptor",
                    ),
                ),
            ],
        ),
    ]
